name: Deploy SvelteKit app

on:
  push:
    branches:
      - main

jobs:
  deploy-primary:
    runs-on: ubuntu-22.04

    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Connect to server, build image, and deploy
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}

            # Write .env file from secret
            echo '${{ secrets.ENV_FILE }}' > .env

            # Pull latest changes from Git
            git checkout main
            git pull

            # Build Docker image
            docker build -t bugspot-app .

            # Check if container exists
            if ! docker ps -a --format '{{.Names}}' | grep -q "^bugspot-app$"; then
              echo "Container bugspot-app does not exist, creating..."
              docker run -d -p 3010:3010 --network host --restart unless-stopped --name bugspot-app bugspot-app
            else
              echo "Container bugspot-app exists, stopping and removing..."
              docker stop bugspot-app || true
              docker rm bugspot-app || true
              docker run -d -p 3010:3010 --network host --restart unless-stopped --name bugspot-app bugspot-app
            fi
          EOF

      - name: Cleanup SSH
        run: rm -rf ~/.ssh